config/routes.rb
Rails.application.routes.draw do
  resources :event_maps do
  	collection do
  		get 'map'
  	end
  end

  
  resources :routers
  get 'home/index'
  get 'home/search'
  devise_for :users
	root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event_map.rb
class EventMap < ApplicationRecord
	
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/router.rb
class Router < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
    validates :username, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username])
    devise_parameter_sanitizer.permit(:update, keys: [:email, :username])
  end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
	def index
		@month = (params[:month] || Time.zone.now.month).to_i
		@year = (params[:year] || Time.zone.now.year).to_i
		@shown_month = Date.civil(@year, @month)
		@event_strips = Event.event_strips_for_month(@shown_month)
	end
end

app/controllers/event_maps_controller.rb
class EventMapsController < ApplicationController
  before_action :set_event_map, only: [:show, :edit, :update, :destroy]
    
  # GET /event_maps
  # GET /event_maps.json
  def index
    @event_maps = EventMap.all
  end

  # GET /event_maps/1
  # GET /event_maps/1.json
  def show
  end

  # GET /event_maps/new
  def new
    @event_map = EventMap.new
  end

  # GET /event_maps/1/edit
  def edit
  end

  # POST /event_maps
  # POST /event_maps.json
  def create
    @event_map = EventMap.new(event_map_params)

    respond_to do |format|
      if @event_map.save
        format.html { redirect_to @event_map, notice: 'Event map was successfully created.' }
        format.json { render :show, status: :created, location: @event_map }
      else
        format.html { render :new }
        format.json { render json: @event_map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_maps/1
  # PATCH/PUT /event_maps/1.json
  def update
    respond_to do |format|
      if @event_map.update(event_map_params)
        format.html { redirect_to @event_map, notice: 'Event map was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_map }
      else
        format.html { render :edit }
        format.json { render json: @event_map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_maps/1
  # DELETE /event_maps/1.json
  def destroy
    @event_map.destroy
    respond_to do |format|
      format.html { redirect_to event_maps_url, notice: 'Event map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_map
      @event_map = EventMap.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_map_params
      params.require(:event_map).permit(:title, :address,:street, :street_number, :postal_code, :city, :state, :country, :start_date, :end_date, :lat, :lng)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	# byebug
  	# @page = EventMap.paginate(page: params[:page], per_page:5)
  end
  def search
  	@event_paginator = EventMap.paginate(page: params[:page], per_page:1)
 	end 	
end

app/controllers/routers_controller.rb
class RoutersController < ApplicationController
  before_action :set_router, only: [:show, :edit, :update, :destroy]

  # GET /routers
  # GET /routers.json
  #Add load_routers and replaced index with the code below
  def load_routers  
     @routers_default = Gmaps4rails.build_markers(Router.all) do |plot, marker|  
        marker.lat plot.latitude  
        marker.lng plot.longitude  

        @status = rand(1..4)  
        @battery = rand(10..90)  
        @ip = "192.168."+rand(0..255).to_s+"."+rand(15..250).to_s  
        @connected = rand(50..100)  

        if @status == 1  
          url_alert = "/good.png"  
          @status == "Normal"  
        else  
          url_alert = "/alert.png"  
        end  

        marker.picture({  
          "url" => url_alert,  
          "width" => 35,  
          "height" => 30  
        })  

        marker.infowindow render_to_string(:partial => "/routers/info",   
          :locals => {:name => plot.name, :battery => @battery, :date => rand(6.months.ago..Time.now), :ip => @ip, :connected => @connected })  
     end  
  end

  def index  
   load_routers  

   @routers = Router.all  
  end

  # GET /routers/1
  # GET /routers/1.json
  def show
  end

  # GET /routers/new
  def new
    @router = Router.new
  end

  # GET /routers/1/edit
  def edit
  end

  # POST /routers
  # POST /routers.json
  def create
    @router = Router.new(router_params)

    respond_to do |format|
      if @router.save
        format.html { redirect_to @router, notice: 'Router was successfully created.' }
        format.json { render :show, status: :created, location: @router }
      else
        format.html { render :new }
        format.json { render json: @router.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routers/1
  # PATCH/PUT /routers/1.json
  def update
    respond_to do |format|
      if @router.update(router_params)
        format.html { redirect_to @router, notice: 'Router was successfully updated.' }
        format.json { render :show, status: :ok, location: @router }
      else
        format.html { render :edit }
        format.json { render json: @router.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routers/1
  # DELETE /routers/1.json
  def destroy
    @router.destroy
    respond_to do |format|
      format.html { redirect_to routers_url, notice: 'Router was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_router
      @router = Router.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def router_params
      params.require(:router).permit(:name, :latitude, :longitude)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/event_maps_helper.rb
module EventMapsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/routers_helper.rb
module RoutersHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/event_maps/_form.html.erb
<%= simple_form_for(@event_map) do |f| %>
  <%= hidden_field_tag :lat, nil, id: "lat" ,value: ""%>
  <%= hidden_field_tag :lng, nil, id: "lng",value: "" %>

  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title, id: "title", value: "" %>
    <%= f.input :address, :label =>"Direction", :input_html => {:id=> 'autocomplete'}, :placeholder => 'Enter address', :onFocus=> "getlocate()" %>
    <%#= f.input :street, :input_html =>{:id => 'route'}, value: "" %>
    <%#= f.input :street_number,  :input_html =>{:id => 'street_number'}, value: "" %>
    <%= f.input :postal_code,  :input_html =>{:id => 'postal_code'}, value: "" %>
    <%= f.input :city,  :input_html =>{:id => 'administrative_area_level_2'}, value: "" %>
    <%= f.input :state,  :input_html =>{:id => 'administrative_area_level_1'}, value: "" %>
    <%= f.input :country, as: :text, :input_html =>{:id => 'country'}, value: "" %>

    <%= f.input :start_date %>
    <%= f.input :end_date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class=> 'btn btn-success' %>
  </div>
<% end %>

<script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyAvuPSxdugPS2FJQibo-i78wVZHWgmKemk&libraries=places"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/geocomplete/1.7.0/jquery.geocomplete.js"></script>

<script type="text/javascript">
  $("#autocomplete").geocomplete()
          .bind("geocode:result", function(event, result){
             a= result.address_components
              for (var i = 0, l=a.length; i < l; i++) 
              {
                if (a[i].types.indexOf('administrative_area_level_2')>-1) 
                {
                  $('#administrative_area_level_2').val(a[i].long_name)
                }
                if (a[i].types.indexOf('administrative_area_level_1')>-1) 
                {
                  $('#administrative_area_level_1').val(a[i].long_name)
                }
                if (a[i].types.indexOf('country')>-1) 
                {
                  $('#country').val(a[i].long_name)
                }
                if (a[i].types.indexOf('postal_code')>-1) 
                {
                  $('#postal_code').val(a[i].long_name)
                }
                if (a[i].types.indexOf('locality')>-1) 
                {
                  $('#locality').val(a[i].long_name)
                }
              }
          });
            

            console.log("Data", result);
            $("#lat").val(result.geometry.viewport.na.j);
            $("#lng").val(result.geometry.viewport.ga.l);


            // $("#route").val(result.address_components[0].long_name);
            // $("#administrative_area_level_2").val(result.address_components[2].long_name);
            // $("#country").val(result.address_components[3].long_name);
          

  
</script>

app/views/event_maps/edit.html.erb
<h1>Editing Event Map</h1>

<%= render 'form', event_map: @event_map %>

<%= link_to 'Show', @event_map, :class=> 'btn' %> |
<%= link_to 'Back', event_maps_path,:class=> 'btn' %>

app/views/event_maps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Event Maps</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Address</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_maps.each do |event_map| %>
      <tr>
        <td><%= event_map.title %></td>
        <td><%= event_map.address %></td>
        <td><%= event_map.start_date %></td>
        <td><%= event_map.end_date %></td>
        <td><%= link_to 'Show', event_map, :class=> 'btn btn-outline-primary'  %></td>
        <td><%= link_to 'Edit', edit_event_map_path(event_map),:class=> 'btn btn-outline-secondary'  %></td>
        <td><%= link_to 'Destroy', event_map, method: :delete, data: { confirm: 'Are you sure?' },:class=> 'btn btn-outline-danger'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event Map', new_event_map_path, :class=>'btn' %>

app/views/event_maps/new.html.erb
<h1>New Event Map</h1>

<%= render 'form', event_map: @event_map %>

<%= link_to 'Back', event_maps_path, :class=> 'btn'%>

app/views/event_maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event_map.title %>
</p>

<p>
  <strong>Address:</strong>
  <%= @event_map.address %>
</p>
<p>
	<strong></strong>
	<%= @event_map.street %>
</p>
<p>
	<strong></strong>
	<%= @event_map.street_number %>
</p>
<p>
	<strong></strong>
	<%= @event_map.postal_code %>
</p>
<p>
	<strong></strong>
	<%= @event_map.city %>
</p>
<p>
	<strong></strong>
	<%= @event_map.state %>
</p>
<p>
	<strong></strong>
	<%= @event_map.country %>
</p>
<p>
	<strong></strong>
	<%= @event_map.lat %>
</p>
<p>
	<strong></strong>
	<%= @event_map.lng %>
</p>
<p>
  <strong>Start date:</strong>
  <%= @event_map.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @event_map.end_date %>
</p>

<%= link_to 'Edit', edit_event_map_path(@event_map),:class=> 'btn'%> |
<%= link_to 'Back', event_maps_path, :class=> 'btn' %>

app/views/home/index.html.erb
<h3 class="text-center">Welcome to Calendar Application </h3><hr>
<div align="center">
  <button type="button" class="btn btn-lg btn-outline-primary"><%= link_to 'Visit website Prototype',    home_search_path %></button>
  <button type="button" class="fa fa-angle-left btn btn-lg btn-outline-primary" style="color: black"><%= link_to 'Visit admin Prototype' %></button>
</div>


<style type="text/css">
	h3{
		margin-top: 50px;
	}
	.btn{
		margin-top: 26px;
		
	}
</style>

<!-- My Project 98223  -->

app/views/home/search.html.erb
<div class="container">
  <form class="navbar-form" role="search">
    <div class="input-group" id="pac-container">
        <!-- <input type="text" class="form-control" placeholder="Search by location" id="pac-input" onFocus= "getlocate()"> -->
        <div class="input-group-btn">
            <button class="btn btn-default" type="submit" ><i class="glyphicon glyphicon-search"></i></button>
        </div>
    </div><br>
  </form>


  
  <div class="h-100">
    <div class="row h-100 justify-content-center align-items-center">
      <div class="col-10">
        <div id="map"></div>
        <div id="infowindow-content">
          <img src="" width="16" height="16" id="place-icon">
          <span id="place-name"  class="title"></span><br>
          <span id="place-address"></span>
        </div>
      </div>   
    </div>
  </div>   
    
<input id="pac-input" class="controls" type="text" placeholder="Search Box">
    <div id="map"></div>
    <script>
      // This example adds a search box to a map, using the Google Place Autocomplete
      // feature. People can enter geographical searches. The search box will return a
      // pick list containing a mix of places and predicted search terms.

      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      function initAutocomplete() {
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -33.8688, lng: 151.2195},
          zoom: 13,
          mapTypeId: 'roadmap'
        });

        // Create the search box and link it to the UI element.
        var input = document.getElementById('pac-input');
        var searchBox = new google.maps.places.SearchBox(input);
        map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

        // Bias the SearchBox results towards current map's viewport.
        map.addListener('bounds_changed', function() {
          searchBox.setBounds(map.getBounds());
        });

        var markers = [];
        // Listen for the event fired when the user selects a prediction and retrieve
        // more details for that place.
        searchBox.addListener('places_changed', function() {
          var places = searchBox.getPlaces();

          if (places.length == 0) {
            return;
          }

          // Clear out the old markers.
          markers.forEach(function(marker) {
            marker.setMap(null);
          });
          markers = [];

          // For each place, get the icon, name and location.
          var bounds = new google.maps.LatLngBounds();
          places.forEach(function(place) {
            if (!place.geometry) {
              console.log("Returned place contains no geometry");
              return;
            }
            var icon = {
              url: place.icon,
              size: new google.maps.Size(71, 71),
              origin: new google.maps.Point(0, 0),
              anchor: new google.maps.Point(17, 34),
              scaledSize: new google.maps.Size(25, 25)
            };

            // Create a marker for each place.
            markers.push(new google.maps.Marker({
              map: map,
              icon: icon,
              title: place.name,
              position: place.geometry.location
            }));

            if (place.geometry.viewport) {
              // Only geocodes have viewport.
              bounds.union(place.geometry.viewport);
            } else {
              bounds.extend(place.geometry.location);
            }
          });
          map.fitBounds(bounds);
        });
      }

    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAvuPSxdugPS2FJQibo-i78wVZHWgmKemk&libraries=places&callback=initAutocomplete"
         async defer></script>


  <!-- <script>
    // function initAutocomplete() {
    //     var locations = [["shop",null,null],["My store","28.755740839001362","77.080078125"],["Try2Mart Shope","23.2599333","77.412615"],["Easy day's","25.6653262","78.4609393"],["Food Hi Food","28.5355161","77.3910265"],["Reliance Fresh","28.6691565","77.4537578"],["Deva's Garments","28.6139391","77.2090212"],["Raj Electronics","28.5355161","77.3910265"],["Heera Sweet","19.0759837","72.8776559"],["Bittern Store","28.6139391","77.2090212"]];
    //     var map = new google.maps.Map(document.getElementById('map'), {
    //       center: {lat: -33.8688, lng: 151.2195},
    //       zoom: 13,
    //       mapTypeId: 'roadmap'
    //     });

    //     // Create the search box and link it to the UI element.
    //     var input = document.getElementById('pac-input');
    //     var searchBox = new google.maps.places.SearchBox(input);
    //     // map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

    //     // Bias the SearchBox results towards current map's viewport.
    //     map.addListener('bounds_changed', function() {
    //       searchBox.setBounds(map.getBounds());
    //     });

    //     var markers = [];
    //     // Listen for the event fired when the user selects a prediction and retrieve
    //     // more details for that place.
    //     searchBox.addListener('places_changed', function() {
    //       var places = searchBox.getPlaces();

    //       if (places.length == 0) {
    //         return;
    //       }

    //       // Clear out the old markers.
    //       markers.forEach(function(marker) {
    //         marker.setMap(null);
    //       });
    //       markers = [];

    //       // For each place, get the icon, name and location.
    //       var bounds = new google.maps.LatLngBounds();
    //       places.forEach(function(place) {
    //         if (!place.geometry) {
    //           console.log("Returned place contains no geometry");
    //           return;
    //         }
    //         var icon = {
    //           url: place.icon,
    //           size: new google.maps.Size(71, 71),
    //           origin: new google.maps.Point(0, 0),
    //           anchor: new google.maps.Point(17, 34),
    //           scaledSize: new google.maps.Size(25, 25)
    //         };

    //         // Create a marker for each place.
    //         markers.push(new google.maps.Marker({
    //           map: map,
    //           icon: icon,
    //           title: place.name,
    //           position: place.geometry.location
    //         }));

    //         if (place.geometry.viewport) {
    //           // Only geocodes have viewport.
    //           bounds.union(place.geometry.viewport);
    //         } else {
    //           bounds.extend(place.geometry.location);
    //         }
    //       });
    //       map.fitBounds(bounds);
    //     });
    //   }








    // function initMap() {
    //   var map = new google.maps.Map(document.getElementById('map'), {
    //     center: {lat: 50.064192, lng: -130.605469},
    //     zoom: 3
    //   });
    //   var card = document.getElementById('pac-card');
    //   var input = document.getElementById('pac-input');
    //   var countries = document.getElementById('country-selector');

    //   map.controls[google.maps.ControlPosition.TOP_RIGHT].push(card);

    //   var autocomplete = new google.maps.places.Autocomplete(input);

    //   // Set initial restrict to the greater list of countries.
    //   autocomplete.setComponentRestrictions(
    //       {'country': ['us', 'pr', 'vi', 'gu', 'mp']});

    //   // Specify only the data fields that are needed.
    //   autocomplete.setFields(
    //       ['address_components', 'geometry', 'icon', 'name']);

    //   var infowindow = new google.maps.InfoWindow();
    //   var infowindowContent = document.getElementById('infowindow-content');
    //   infowindow.setContent(infowindowContent);
    //   var marker = new google.maps.Marker({
    //     map: map,
    //     anchorPoint: new google.maps.Point(0, -29)
    //   });

    //   autocomplete.addListener('place_changed', function() {
    //     infowindow.close();
    //     marker.setVisible(false);
    //     var place = autocomplete.getPlace();
    //     if (!place.geometry) {
    //       // User entered the name of a Place that was not suggested and
    //       // pressed the Enter key, or the Place Details request failed.
    //       window.alert("No details available for input: '" + place.name + "'");
    //       return;
    //     }

    //     // If the place has a geometry, then present it on a map.
    //     if (place.geometry.viewport) {
    //       map.fitBounds(place.geometry.viewport);
    //     } else {
    //       map.setCenter(place.geometry.location);
    //       map.setZoom(17);  // Why 17? Because it looks good.
    //     }
    //     marker.setPosition(place.geometry.location);
    //     marker.setVisible(true);

    //     var address = '';
    //     if (place.address_components) {
    //       address = [
    //         (place.address_components[0] && place.address_components[0].short_name || ''),
    //         (place.address_components[1] && place.address_components[1].short_name || ''),
    //         (place.address_components[2] && place.address_components[2].short_name || '')
    //       ].join(' ');
    //     }

    //     infowindowContent.children['place-icon'].src = place.icon;
    //     infowindowContent.children['place-name'].textContent = place.name;
    //     infowindowContent.children['place-address'].textContent = address;
    //     infowindow.open(map, marker);
    //   });

    //   // Sets a listener on a given radio button. The radio buttons specify
    //   // the countries used to restrict the autocomplete search.
    //   function setupClickListener(id, countries) {
    //     var radioButton = document.getElementById(id);
    //     radioButton.addEventListener('click', function() {
    //       autocomplete.setComponentRestrictions({'country': countries});
    //     });
    //   }

    //   setupClickListener('changecountry-usa', 'us');
    //   setupClickListener(
    //       'changecountry-usa-and-uot', ['us', 'pr', 'vi', 'gu', 'mp']);
    // }
  </script> -->
  <!-- <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAvuPSxdugPS2FJQibo-i78wVZHWgmKemk&libraries=places&callback=initAutocomplete"
      async defer></script> -->

  <section>
    <div class="h-100">
      <div class="row h-100 justify-content-center align-items-center">
        <div class="col-10">
          <h3 align="center">Upcoming Events</h3>
          <% @event_paginator.all.each do |event|%>
            <div class="card" style="width: 18rem;">
              <div class="card-body">
                <h5 class="card-title"><%= event.title %></h5>
                <p class="card-text"><%= event.address %></p>
                <p class="card-text"><%= event.start_date %></p>
                <p class="card-text"><%= event.end_date %></p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
              </div>
            </div>
            <% end %>
        </div>   
      </div>
    </div> <br> 
    <div class= "digg_pagination row h-100 justify-content-center align-items-center">
      <%= will_paginate @event_paginator, renderer: BootstrapPagination::Rails, previous_label: "Older", next_label: "Newer", inner_window: 1, outer_window: 0 %> 
    </div> 
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalendarApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'true' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'true' %>
    <%= tag :meta, name: 'google_maps', content: 'AIzaSyAvuPSxdugPS2FJQibo-i78wVZHWgmKemk' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <%  end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <div class="container">
      <div class="row">
        <div class="col-12">
          <%= render partial: 'shared/navigation_bar' %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>
 

app/views/routers/edit.html.erb
<h1>Editing Router</h1>

<%= render 'form', router: @router %>

<%= link_to 'Show', @router %> |
<%= link_to 'Back', routers_path %>

app/views/routers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Routers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routers.each do |router| %>
      <tr>
        <td><%= router.name %></td>
        <td><%= router.address %></td>
        <td><%= router.latitude %></td>
        <td><%= router.longitude %></td>
        <td><%= link_to 'Show', router %></td>
        <td><%= link_to 'Edit', edit_router_path(router) %></td>
        <td><%= link_to 'Destroy', router, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Router', new_router_path %>


<div style='width: 800px;'>  
  <div id="map" style='width: 800px; height: 400px;'></div>  
</div>  

<!-- <script type="text/javascript">  
handler = Gmaps.build('Google');  
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){  
  markers = handler.addMarkers([  
    {  
      "lat": 28.7041,  
      "lng": -121.8806499,  
      "picture": {  
        "width":  32,  
        "height": 32  
      },  
      "infowindow": "SJSU"  
    }  
  ]);  
  handler.bounds.extendWith(markers);  
  handler.fitMapToBounds();  
});  
</script>

<script type="text/javascript">  
handler = Gmaps.build('Google');  
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){  
    markers = handler.addMarkers(<%=raw @routers_default.to_json %>);  
    handler.bounds.extendWith(markers);  
    handler.fitMapToBounds();  
});  
</script> -->
<h3 class="text-center" style="margin-top: 20px;">Upcoming events</h3>
<div id="calendar"></div>

app/views/routers/new.html.erb
<h1>New Router</h1>

<%= render 'form', router: @router %>

<%= link_to 'Back', routers_path %>

app/views/routers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @router.name %>
</p>
<p>
  <strong>Address</strong>
  <%= @router.address %>
</p>
<p>
  <strong>Latitude:</strong>
  <%= @router.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @router.longitude %>
</p>

<%= link_to 'Edit', edit_router_path(@router) %> |
<%= link_to 'Back', routers_path %>
<p><hr>

  



<p>
	<div id="map">
    <script src="//maps.google.com/maps/api/js?key=AIzaSyAvuPSxdugPS2FJQibo-i78wVZHWgmKemk"></script> 
     <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAvuPSxdugPS2FJQibo-i78wVZHWgmKemk&libraries=places&callback=initAutocomplete"
         async defer></script>

    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>  
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
    <script src='//underscorejs.org/underscore-min.js' type='text/javascript'></script>
  </div>
</p>

<% provide :head_tags do %>
    <script>
      document.addEventListener("DOMContentLoaded", function(){
          initMap(<%=@router.latitude%>, <%=@router.longitude%>)
      });
    </script>
<% end %>